name: Deploy
on: [ push ]

jobs:
  rspec:
    runs-on: ubuntu-latest
    steps:
      - name: Rspec
        run: echo "Rspec"

  docker:
    runs-on: ubuntu-latest
    needs: rspec
    environment: 
      name: dev
    steps:
      - name: Login Docker Hub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build and Push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./Dockerfile
          builder: ${{ steps.buildx.outputs.name }}
          push: true
          tags:  prgs/teste:latest
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}

