on:
  push:
    branches:
      - 'master'

jobs:
  rspec:
    runs-on: self-hosted
    container: node:10.16-jessie
    steps:
      - name: Rspec
        run: echo "Rspec"

  docker:
    runs-on: self-hosted
    needs: rspec
    environment: 
      name: dev
    steps:
      - uses: actions/checkout@v1
      - name: Login Docker Hub    
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build e Push 
        run: |
          docker build . --file docker/Dockerfile --tag prgs/app:latest
          docker push prgs/app:latest

# docker:
#   runs-on: ubuntu-latest
#   needs: rspec
#   environment: 
#     name: dev
#   steps:
#     - name: Login Docker Hub
#       uses: docker/login-action@v1 
#       with:
#         username: ${{ secrets.DOCKER_HUB_USERNAME }}
#         password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
#     - name: Checkout
#       uses: actions/checkout@v1
#     - name: Publish image
#       uses: docker/build-push-action@v1
#       with:
#         repository: prgs/teste
#         tag_with_ref: true
#         tag_with_sha: true

# jobs:
#   docker:
#     runs-on: ubuntu-latest
#     environment: 
#       name: dev
#     steps:
#       -
#         name: Set up QEMU
#         uses: docker/setup-qemu-action@v1
#       -
#         name: Set up Docker Buildx
#         uses: docker/setup-buildx-action@v1
#       -
#         name: Login to DockerHub
#         uses: docker/login-action@v1 
#         with:
#           username: ${{ secrets.DOCKER_HUB_USERNAME }}
#           password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
#       -
#         name: Build and push
#         id: docker_build
#         uses: docker/build-push-action@v2
#         with:
#           push: true
#           tags: prgs/teste:latest