env:
  RUBYOPT: "-W0"
  TZ: "America/Sao_Paulo"
  DEBIAN_FRONTEND: "noninteractive"

name: github-actions

on:
  push:
    branches:
      - 'master'

jobs:
  rspec:
    runs-on: [ rspec ]

    services:
      redis:
        image: redis:2.8
        ports:
          - 6379:6379
        options: --entrypoint redis-server

      db:
        image: postgres:latest
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Run rubocop
        run: pwd

      # - name: Boot Local - Install Dependencies Runner
      #   if: ${{ env.ACT }}
      #   run: |
      #     npm i -g yarn
      #     apt-get update
      #     apt-get -yqq install libgconf-2-4 libatk1.0-0 libatk-bridge2.0-0 libgdk-pixbuf2.0-0 libgtk-3-0 libgbm-dev libnss3-dev libxss-dev libasound2 libxshmfence-dev postgresql postgresql-contrib redis-server        
      #     service postgresql start
      #     service redis-server start



  # docker:
  #   runs-on: [ docker ]
  #   needs: rspec
  #   environment: 
  #     name: dev
  #   steps:
  #     - uses: actions/checkout@v1
  #     - name: Login Docker Hub    
  #       uses: docker/login-action@v1 
  #       with:
  #         username: ${{ secrets.DOCKER_HUB_USERNAME }}
  #         password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

  #     - name: Build e Push 
  #       run: |
  #         docker build . --file docker/Dockerfile --tag prgs/app:latest
  #         docker push prgs/app:latest